spring:
  datasource:
    url: jdbc:h2:file:~/data/invoice_program
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    default-property-inclusion: non_null

  mail:
    host: smtp.gmail.com
    port: 587
    username: invoicebysebaa@gmail.com
    password: zaq1@WSXX
    personal_title: InvoiceProgramBySebaa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

cron.expression: 0 0 12 ? * TUE *
