spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoices_program?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: admin_user
    password: admin_password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null


# MAIL CONFIGURATION
invoice:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  properties:
    smtp:
      auth: true
      tls_enable: true

#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=${MAIL_USERNAME}
#  spring.mail.password=${MAIL_PASSWORD}
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true