spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoices_program?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: admin_user
    password: admin_password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null