spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoices_program?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: admin_user
    password: admin_password
  jpa:
    database: mysql
    show-sql: true
    hibernate:mail:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null

  mail:
    host: smtp.gmail.com
    port: 587
    username: invoicebysebaa@gmail.com
    password: zaq1@WSXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
