spring:
  datasource:
    url: jdbc:h2:file:~/data/invoice_program
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    default-property-inclusion: non_null

  mail:
    host:  # <- host serwera smtp. Jeśli nie możesz znaleść swoich ustawień SMTP w na swojej poczcie być może ten link Ci pomoże -> https://www.blulink.pl/serwery-poczty-smtp,-pop3,-imap,125.html
    port: 587 # <- port serwera smtp. Domyślnie jest to ten port. Jeśli jest inny niż już wpisany, zmień go.
    username:  # <- login użytkownika
    password:  # <- hasło użytkownika
    personal_title: InvoiceProgramBySebaa # <- dowolna nazwa nadającego, zamiast zwykłego adresu email.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

client.verify:  # <- token weryfikacyjny w Google, potrzebny do weryfikacji tokenu logującego z przeglądarki. Aby stworzyć konto podążaj za tymi instrukcjami: https://www.youtube.com/watch?v=YNwx1nE1boo
cron.expression: 0 0 12 * * TUE # <- domyślna wartość automatycznych wiadomości przypoiminajacych o fakturze. Obecnie jest to w każdy wtorek o godzinie 12.00
