DELETE FROM business_details;

INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (1, 'TEST_COMPANY 1', 'Kielecka #1', '12-341', 'Kielce', 'POLAND', 123456781, 'example_#1@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (2, 'TEST_COMPANY 2', 'Kielecka #2', '12-342', 'Kielce', 'POLAND', 123456782, 'example_#2@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (3, 'TEST_COMPANY 3', 'Kielecka #3', '12-343', 'Kielce', 'POLAND', 123456783, 'example_#3@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (4, 'TEST_COMPANY 4', 'Kielecka #4', '12-344', 'Kielce', 'POLAND', 123456784, 'example_#4@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (5, 'TEST_COMPANY 5', 'Kielecka #5', '12-345', 'Kielce', 'POLAND', 123456785, 'example_#5@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (6, 'TEST_COMPANY 6', 'Kielecka #6', '12-346', 'Kielce', 'POLAND', 123456786, 'example_#6@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (7, 'TEST_COMPANY 7', 'Kielecka #7', '12-347', 'Kielce', 'POLAND', 123456787, 'example_#7@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (8, 'TEST_COMPANY 8', 'Kielecka #8', '12-348', 'Kielce', 'POLAND', 123456788, 'example_#8@test');
INSERT INTO business_details(ID, FULL_NAME, ADDRESS, POSTAL_CODE, CITY, COUNTRY, TAX_ID, EMAIL_ADDRESS) VALUES (9, 'TEST_COMPANY 9', 'Kielecka #9', '12-349', 'Kielce', 'POLAND', 123456789, 'example_#9@test');
