CREATE TABLE IF NOT EXISTS BUSINESS_DETAILS
(
    ID            SERIAL PRIMARY KEY,
    FULL_NAME     VARCHAR(150) NOT NULL,
    ADDRESS       VARCHAR(80)  NOT NULL,
    POSTAL_CODE   VARCHAR(6)   NOT NULL,
    CITY          VARCHAR(50)  NOT NULL,
    TAX_ID        INT(11)      NOT NULL,
    EMAIL_ADDRESS VARCHAR(100) NOT NULL
);

-- TODO: Jeśli starczy czasu
-- CREATE TABLE IF NOT EXISTS USERS
-- (
--     ID          SERIAL PRIMARY KEY,
--     BUSINESS_ID INT,
--     USERNAME    VARCHAR(50)  NOT NULL,
--     PASSWORD    VARCHAR(100) NOT NULL,
--     EMAIL       VARCHAR(80)  NOT NULL,
--     ENABLED     VARCHAR(45)  NOT NULL,
--     GROUP_NAME  VARCHAR(45)  NOT NULL,
--     FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS_DETAILS (ID)
-- );

CREATE TABLE IF NOT EXISTS CUSTOMERS
(
    ID                   SERIAL PRIMARY KEY,
    BUSINESS_ID          INT          NOT NULL,
    CUSTOMER_NAME        VARCHAR(80)  NOT NULL,
    BUSINESS_NAME        VARCHAR(150) NOT NULL,
    BUSINESS_ADDRESS     VARCHAR(80)  NOT NULL,
    BUSINESS_POSTAL_CODE VARCHAR(6)   NOT NULL,
    BUSINESS_CITY        VARCHAR(50)  NOT NULL,
    BUSINESS_COUNTRY     VARCHAR(80)  NOT NULL,
    TAX_ID               INT(11)      NOT NULL,
    EMAIL_ADDRESS        VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS INVOICES
(
    ID                         SERIAL PRIMARY KEY,
    BUSINESS_ID                INT            NOT NULL,
    CUSTOMER_ID                INT            NOT NULL,
    INVOICE_NUMBER             VARCHAR(80)    NOT NULL,
    CREATED_DATE               DATE           NOT NULL,
    ISSUE_DATE                 DATE           NOT NULL,
    DUE_DATE                   DATE           NOT NULL,
    PAYMENT_METHOD             VARCHAR(45)    NOT NULL,
    GROSS_PRICE                DECIMAL(10, 2) NOT NULL,
    OTHER_CURRENCY_NAME        VARCHAR(5),
    OTHER_CURRENCY_GROSS_PRICE DECIMAL(10, 2),
    EXCHANGE_RATE              DECIMAL(10, 5),
    FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS_DETAILS (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
);

CREATE TABLE IF NOT EXISTS INVOICES_GTU
(
    ID         SERIAL PRIMARY KEY,
    INVOICE_ID INT        NOT NULL,
    GTU_TYPE   VARCHAR(6) NOT NULL,
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(ID)
);

CREATE TABLE IF NOT EXISTS INVOICES_ITEMS
(
    ID          SERIAL PRIMARY KEY,
    INVOICE_ID  INT            NOT NULL,
    NAME        VARCHAR(80)    NOT NULL,
    UI          VARCHAR(5)     NOT NULL,
    QUANTITY    INT(10)        NOT NULL,
    NET_PRICE   DECIMAL(10, 2) NOT NULL,
    TAX_VALUE   INT(3)         NOT NULL,
    GROSS_PRICE DECIMAL(10, 2) NOT NULL,
    DISCOUNT    INT(3),
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES (ID) ON DELETE CASCADE
);
